environments:
  gocd_images:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - ssh-mount-dummy
pipelines:
  ssh-mount-dummy:
    group: gocd_images
    locking: off
    materials:
      gocd_agent_pypi_git:  # this is the name of material
        # says about type of material and url at once
        name: ssh-mount-dummy
        git: https://github.com/rasmunk/docker-ssh-mount-dummy.git
        branch: master
        destination: ssh-mount-dummy
      publish_docker_git:  # this is the name of material
        # says about type of material and url at once
        name: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-docker-scripts
    parameters:
      IMAGE: docker-ssh-mount-dummy
      ARGS: ''
      COMMIT_TAG: GO_REVISION_GOCD_AGENT_PYPI_GIT
      DEFAULT_TAG: latest
      SRC_DIRECTORY: ssh-mount-dummy
      TEST_DIRECTORY: ssh-mount-dummy
      PUSH_DIRECTORY: publish-docker-scripts
    template: docker_image
