services:
  agent:
    image: ucphhpc/ssh-mount-dummy:${TAG}
    init: true
    build:
      context: ./
      dockerfile: ssh-mount-dummy/Dockerfile.${TAG}
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
        AUTHORIZED_KEYS_DIR: ${AUTHORIZED_KEYS_DIR}
    ports:
      - "2222:22"
    env_file:
      - .env
    volumes:
      - ./authorized-keys:${AUTHORIZED_KEYS_DIR}:ro
