version: '3.7'

services:
  agent:
    image: ucphhpc/ssh-mount-dummy:${TAG}
    init: true
    build:
      context: ./
      dockerfile: ssh-mount-dummy/Dockerfile.${TAG}
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    ports:
      - "2222:22"
    env_file:
      - .env
