version: '3.7'

services:
  agent:
    image: ucphhpc/ssh-mount-dummy:$TAG
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TAG: ${TAG}
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    ports:
      - "2222:22"
    env_file:
      - .env