FROM {{ parent }}
LABEL MAINTAINER="Rasmus Munk <rasmus.munk@nbi.ku.dk>"

ARG USERNAME=mountuser
ARG PASSWORD=Passw0rd!

RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
    openssh-server \
    python3-dev \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Remove generated host SSH keys
RUN rm -fr /etc/ssh/ssh_host_*

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd \
    && mkdir -p /run/sshd

COPY main.py /app/main.py
COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install setuptools wheel --break-system-packages \
    && pip3 install -r requirements.txt --break-system-packages

RUN useradd -ms /bin/bash ${USERNAME}
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd

EXPOSE 22

# Add the Docker Entrypoing script
ADD docker-entry.sh /app/docker-entry.sh
RUN chmod +x /app/docker-entry.sh
CMD ["bash", "/app/docker-entry.sh"]
